// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for development - replace with generated code later.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// Device represents a charging device
type Device struct {
	Id              string `json:"id,omitempty"`
	Vendor          string `json:"vendor,omitempty"`
	Model           string `json:"model,omitempty"`
	SerialNumber    string `json:"serial_number,omitempty"`
	FirmwareVersion string `json:"firmware_version,omitempty"`
	Status          string `json:"status,omitempty"`
}

// GetDeviceRequest for getting a single device
type GetDeviceRequest struct {
	Id string `json:"id,omitempty"`
}

// GetDeviceResponse returns a device
type GetDeviceResponse struct {
	Device *Device `json:"device,omitempty"`
}

// ListDevicesRequest for listing devices
type ListDevicesRequest struct {
	PageSize  int32  `json:"page_size,omitempty"`
	PageToken string `json:"page_token,omitempty"`
}

// ListDevicesResponse returns a list of devices
type ListDevicesResponse struct {
	Devices       []*Device `json:"devices,omitempty"`
	NextPageToken string    `json:"next_page_token,omitempty"`
}

// UpdateDeviceStatusRequest for updating device status
type UpdateDeviceStatusRequest struct {
	Id     string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
}

// UpdateDeviceStatusResponse confirms status update
type UpdateDeviceStatusResponse struct {
	Success bool `json:"success,omitempty"`
}

// StreamDeviceEventsRequest for streaming device events
type StreamDeviceEventsRequest struct {
	DeviceIds []string `json:"device_ids,omitempty"`
}

// DeviceEvent represents a device event
type DeviceEvent struct {
	DeviceId  string `json:"device_id,omitempty"`
	EventType string `json:"event_type,omitempty"`
	Timestamp int64  `json:"timestamp,omitempty"`
	Payload   string `json:"payload,omitempty"`
}

// DeviceServiceClient is the client API for DeviceService
type DeviceServiceClient interface {
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	UpdateDeviceStatus(ctx context.Context, in *UpdateDeviceStatusRequest, opts ...grpc.CallOption) (*UpdateDeviceStatusResponse, error)
	StreamDeviceEvents(ctx context.Context, in *StreamDeviceEventsRequest, opts ...grpc.CallOption) (DeviceService_StreamDeviceEventsClient, error)
}

// DeviceServiceServer is the server API for DeviceService
type DeviceServiceServer interface {
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	UpdateDeviceStatus(context.Context, *UpdateDeviceStatusRequest) (*UpdateDeviceStatusResponse, error)
	StreamDeviceEvents(*StreamDeviceEventsRequest, DeviceService_StreamDeviceEventsServer) error
}

// UnimplementedDeviceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, nil
}

func (UnimplementedDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, nil
}

func (UnimplementedDeviceServiceServer) UpdateDeviceStatus(context.Context, *UpdateDeviceStatusRequest) (*UpdateDeviceStatusResponse, error) {
	return nil, nil
}

func (UnimplementedDeviceServiceServer) StreamDeviceEvents(*StreamDeviceEventsRequest, DeviceService_StreamDeviceEventsServer) error {
	return nil
}

// DeviceService_StreamDeviceEventsServer is for streaming
type DeviceService_StreamDeviceEventsServer interface {
	Send(*DeviceEvent) error
	grpc.ServerStream
}

// DeviceService_StreamDeviceEventsClient is for streaming
type DeviceService_StreamDeviceEventsClient interface {
	Recv() (*DeviceEvent, error)
	grpc.ClientStream
}

// RegisterDeviceServiceServer registers the server
func RegisterDeviceServiceServer(s *grpc.Server, srv DeviceServiceServer) {
	// Stub - in production, use generated code
}
