run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - mocks

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - bodyclose
    - noctx
    - gosec
    - gocritic
    - revive
    - errorlint
    - wrapcheck

  disable:
    - gochecknoglobals
    - gochecknoinits
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - lll
    - wsl
    - nlreturn
    - gomnd
    - exhaustive
    - exhaustruct
    - varnamelen
    - ireturn

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/seu-repo/sigec-ve

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code

  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G304 # File path provided as taint input

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithStack(
    ignorePackageGlobs:
      - github.com/seu-repo/sigec-ve/*

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - wrapcheck
        - gocritic

    # Exclude some linters from mocks
    - path: mocks/
      linters:
        - unused
        - revive

    # Exclude main.go from some checks
    - path: cmd/
      linters:
        - wrapcheck

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

severity:
  default-severity: warning
  rules:
    - linters:
        - errcheck
        - gosec
      severity: error
